# Generated by Django 3.0.5 on 2021-05-16 08:41

from django.db import migrations, models
import djongo.models.fields
import mongoapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('emp_id', models.PositiveIntegerField()),
                ('address', djongo.models.fields.EmbeddedField(model_container=mongoapp.models.Address)),
            ],
        ),
    ]
