# Generated by Django 3.0.5 on 2021-05-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
